-- competitions --
INSERT INTO competitions (name, country) VALUES
('La Liga', 'España'),
('Premier League', 'Inglaterra'),
('Serie A', 'Italia'),
('Bundesliga', 'Alemania'),
('Ligue 1', "Francia"),
('Champions League', 'Europa');
-- teams --
INSERT INTO teams (team_name, sport) VALUES
-- La Liga --
('Barcelona', 'Fútbol'),
('Atlético de Madrid', 'Fútbol'),
('Real Madrid', 'Fútbol'),
('Girona', 'Fútbol'),
('Athletic', 'Fútbol'),
('Real Sociedad', 'Fútbol'),
('Betis', 'Fútbol'),
('Valencia C.F.', 'Fútbol'),
('Villarreal', 'Fútbol'),
('Sevilla', 'Fútbol'),
('Getafe', 'Fútbol'),
('Rayo Vallecano', 'Fútbol'),
('Osasuna', 'Fútbol'),
('U.D. Las Palmas', 'Fútbol'),
('Alavés', 'Fútbol'),
('R.C.D. Mallorca', 'Fútbol'),
('Celta de Vigo', 'Fútbol'),
('Valladolid', 'Fútbol'),
('Leganés', 'Fútbol'),
('RCD Espanyol', 'Fútbol'),
-- Premier League --
('Arsenal', 'Football'),
('Aston Villa', 'Football'),
('Bournemouth', 'Football'),
('Brentford', 'Football'),
('Brighton', 'Football'),
('Chelsea', 'Football'),
('Crystal Palace', 'Football'),
('Everton', 'Football'),
('Fulham', 'Football'),
('Ipswich', 'Football'),
('Leicester City', 'Football'),
('Liverpool', 'Football'),
('Manchester City', 'Football'),
('Manchester United', 'Football'),
('Newcastle', 'Football'),
('Nottingham Forest', 'Football'),
('Southampton', 'Football'),
('Tottenham', 'Football'),
('West Ham', 'Football'),
('Wolves', 'Football'),
-- Serie A --
('Atalanta', 'Fútbol'),
('Bolonia', 'Fútbol'),
('Cagliari', 'Fútbol'),
('Como', 'Fútbol'),
('Empoli', 'Fútbol'),
('Fiorentina', 'Fútbol'),
('Genoa', 'Fútbol'),
('Hellas Verona', 'Fútbol'),
('Inter', 'Fútbol'),
('Juventus', 'Fútbol'),
('Lazio', 'Fútbol'),
('Lecce', 'Fútbol'),
('Milan', 'Fútbol'),
('Monza', 'Fútbol'),
('Napoli', 'Fútbol'),
('Parma', 'Fútbol'),
('Roma', 'Fútbol'),
('Torino', 'Fútbol'),
('Udinese', 'Fútbol'),
('Venezia', 'Fútbol'),
-- BundesLiga --
('Augsburgo', 'Fútbol'),
('Leverkusen', 'Fútbol'),
('Bayern de Múnich', 'Fútbol'),
('Bochum', 'Fútbol'),
('B. Dortmund', 'Fútbol'),
('B. Mönchengladbach', 'Fútbol'),
('Frankfurt', 'Fútbol'),
('Friburgo', 'Fútbol'),
('Heidenheim', 'Fútbol'),
('Hoffenheim', 'Fútbol'),
('KSV Holstein', 'Fútbol'),
('Mainz 05', 'Fútbol'),
('RB Leipzig', 'Fútbol'),
('St. Pauli', 'Fútbol'),
('Stuttgart', 'Fútbol'),
('FC Unión Berlín', 'Fútbol'),
('Werder Bremen', 'Fútbol'),
('Wolfsburgo', 'Fútbol'),
-- Ligue One --
('Angers', 'Fútbol'),
('Auxerre', 'Fútbol'),
('Le Havre', 'Fútbol'),
('Lens', 'Fútbol'),
('LOSC', 'Fútbol'),
('Mónaco', 'Fútbol'),
('Montpellier', 'Fútbol'),
('Nantes', 'Fútbol'),
('Niza', 'Fútbol'),
('Lyon', 'Fútbol'),
('Marsella', 'Fútbol'),
('PSG', 'Fútbol'),
('Racing de Estrasburgo', 'Fútbol'),
('Rennes', 'Fútbol'),
('Saint-Étienne', 'Fútbol'),
('Stade Brestois', 'Fútbol'),
('Reims', 'Fútbol'),
('Toulouse', 'Fútbol'),
-- another teams --
('Sporting Lisboa', 'Fútbol'),
('Benfica', 'Fútbol'),
('PSV', 'Fútbol'),
('Feyenoord', 'Fútbol'),
('Sturm', 'Fútbol'),
('RB Salzburg', 'Fútbol'),
('Club Brujas', 'Fútbol'),
('Celtic F.C.', 'Fútbol'),
('Shakhtar', 'Fútbol'),
('Sparta Praha', 'Fútbol'),
('Young Boys', 'Fútbol'),
('Dinamo Zagreb', 'Fútbol'),
('Estrella Roja', 'Fútbol'),
('Slovan Bratislava', 'Fútbol');
